export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  GONE: "GONE",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Drop & Item errors
  DROP_NOT_FOUND: "DROP_NOT_FOUND",
  DROP_EXPIRED: "DROP_EXPIRED",
  DROP_REVOKED: "DROP_REVOKED",
  DROP_DELETING: "DROP_DELETING",
  EMPTY_DROP: "EMPTY_DROP",
  INVALID_DRAFT_TOKEN: "INVALID_DRAFT_TOKEN",
  DRAFT_EXPIRED: "DRAFT_EXPIRED",
  DRAFT_ALREADY_COMMITTED: "DRAFT_ALREADY_COMMITTED",
  CODE_GENERATION_FAILED: "CODE_GENERATION_FAILED",
  INVALID_CODE_FORMAT: "INVALID_CODE_FORMAT",

  // File & Upload errors
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  TOTAL_FILE_SIZE_EXCEEDED: "TOTAL_FILE_SIZE_EXCEEDED",
  MAX_FILES_EXCEEDED: "MAX_FILES_EXCEEDED",
  TEXT_TOO_LARGE: "TEXT_TOO_LARGE",
  DANGEROUS_FILE_REJECTED: "DANGEROUS_FILE_REJECTED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_NOT_VERIFIED: "FILE_NOT_VERIFIED",
  FILE_OBJECT_MISSING: "FILE_OBJECT_MISSING",
  FILE_SIZE_MISMATCH: "FILE_SIZE_MISMATCH",
  FILE_TYPE_MISMATCH: "FILE_TYPE_MISMATCH",

  // Admin & Auth errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_SESSION: "INVALID_SESSION",
  CSRF_DETECTED: "CSRF_DETECTED",
  INVALID_EXPIRY: "INVALID_EXPIRY",
  SETTINGS_UPDATE_FAILED: "SETTINGS_UPDATE_FAILED",
  RATE_LIMITED: "RATE_LIMITED"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
